from .models import Establishment

ESTABLISHMENTS = [
    Establishment(title="Aquarium", id="aquarium"),
    Establishment(title="Art Gallery", id="art_gallery"),
    Establishment(title="Bakery", id="bakery"),
    Establishment(title="Bar", id="bar"),
    Establishment(title="Beauty Salon", id="beauty_salon"),
    Establishment(title="Bowling Alley", id="bowling_alley"),
    Establishment(title="Bus Station", id="bus_station"),
    Establishment(title="Cafe", id="cafe"),
    Establishment(title="Church", id="church"),
    Establishment(title="Clothing Store", id="clothing_store"),
    Establishment(title="Convenience Store", id="convenience_store"),
    Establishment(title="Department Store", id="department_store"),
    Establishment(title="Florist", id="florist"),
    Establishment(title="Gas Station", id="gas_station"),
    Establishment(title="Gym", id="gym"),
    Establishment(title="Library", id="library"),
    Establishment(title="Light Rail Station", id="light_rail_station"),
    Establishment(title="Meal Delivery", id="meal_delivery"),
    Establishment(title="Meal Takeaway", id="meal_takeaway"),
    Establishment(title="Mosque", id="mosque"),
    Establishment(title="Movie Theater", id="movie_theater"),
    Establishment(title="Museum", id="museum"),
    Establishment(title="Night Club", id="night_club"),
    Establishment(title="Park", id="park"),
    Establishment(title="Restaurant", id="restaurant"),
    Establishment(title="Shopping Mall", id="shopping_mall"),
    Establishment(title="Spa", id="spa"),
    Establishment(title="Stadium", id="stadium"),
    Establishment(title="Store", id="store"),
    Establishment(title="Subway Station", id="subway_station"),
    Establishment(title="Supermarket", id="supermarket"),
    Establishment(title="Tourist Attraction", id="tourist_attraction"),
    Establishment(title="Train Station", id="train_station"),
    Establishment(title="Transit Station", id="transit_station"),
    Establishment(title="University", id="university"),
    Establishment(title="Zoo", id="zoo"),
]